version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local

  localstack:
    image: localstack/localstack:0.13.2
    ports:
      - "7000:4566"
      - "17000:4571"
    environment:
      - SERVICES=sns,sqs
      - DATA_DIR=/data/localstack
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EAGER_SERVICE_LOADING=true

  awsinit:
    depends_on:
      - localstack
    build:
      context: ../aws