name: Deploy AWS CDK

on:
  workflow_dispatch

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Instal npm
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: Instal CDK
      run: 'sudo npm install -g aws-cdk'

    - name: CDK Synth
      run: cdk synth
      working-directory: shop-keeper-infrastructure

    - name: CDK Deploy
      run: cdk deploy --require-approval never --parameters imageTag=${{ github.sha }}
      working-directory: shop-keeper-infrastructure
